Anidar/Models/DbModel.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anidar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnidarEntities : DbContext
    {
        public AnidarEntities()
            : base("name=AnidarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Persona> Personas { get; set; }
    }
}

Anidar/Models/DbModel.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Public\Public Dropbox\Dropbox\Privado\Documentos\Visual Studio 2015\Projects\Anidar\Anidar\Models\DbModel.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

Anidar/Models/DbModel.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Anidar/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Anidar.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddOrEdit()
        {
            ViewBag.Message = "Inscribir.";

            return View();
        }

        public ActionResult Inscripciones()
        {
            ViewBag.Message = "Inscripciones.";

            return View();
        }
    }
}

Anidar/Controllers/PersonasController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Anidar.Models;

namespace Anidar.Controllers
{
    public class PersonasController : Controller
    {
        [HttpGet]
        public ActionResult AddOrEdit(int id=0)
        {
            Persona personaModel = new Persona();
            return View(personaModel);
        }
        
        private AnidarEntities db = new AnidarEntities();

        public ActionResult Inscripciones()
        {
            return View(db.Personas.ToList());
        }

        [HttpPost]
        public ActionResult AddOrEdit(Persona personaModel)
        {
            using (AnidarEntities dbModel = new AnidarEntities())
            {
                dbModel.Personas.Add(personaModel);
                dbModel.SaveChanges();
            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Ingreso correcto.";
            return View("AddOrEdit", new Persona());
        }
    }
}

Anidar/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Anidar/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Anidar/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}

<div class="jumbotron">
    <h1>Inscripción</h1>
    <p class="lead">Inscripción de mujeres embarazadas al servicio de Anidar.</p>
    <p><a href="https://www.mills.com.ar/Anidar/Personas/AddOrEdit" class="btn btn-primary btn-lg" style="background-color:#000">Inscribir &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Inscripciones realizadas</h2>
        <p>
            Ver todas las inscripciones realizadas al sistema.
        </p>
        <p><a class="btn btn-default" href="https://www.mills.com.ar/Anidar/Personas/Inscripciones">Ver inscripciones &raquo;</a></p>
    </div>    
</div>

Anidar/Views/Personas/AddOrEdit.cshtml
@model Anidar.Models.Persona

@{
    ViewBag.Title = "Ingreso";
}

<h2>Ingreso de personas</h2>


@using (Html.BeginForm("AddOrEdit", "Personas", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Persona</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SemanasEmabarazo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SemanasEmabarazo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SemanasEmabarazo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Domicilio, htmlAttributes: new { @class = "control-label col-md-2" }) 
        <div class="col-md-10">
            @Html.EditorFor(model => model.Domicilio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Domicilio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Instagram, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Instagram, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Instagram, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Ingresar" class="btn btn-default" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class="label-success">@ViewBag.SuccessMessage</label>
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Anidar/Views/Personas/Inscripciones.cshtml
@model IEnumerable<Anidar.Models.Persona>

@{
    ViewBag.Title = "Inscripciones";
}

<h2>Inscripciones</h2>


@using (Html.BeginForm("Inscripciones", "Personas", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div style="width:100%; max-width:100%; overflow-x:auto;">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Edad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SemanasEmabarazo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Domicilio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Instagram)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Edad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SemanasEmabarazo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Domicilio)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefono)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Instagram)
                </td>
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                    </td>*@
            </tr>
        }
    </table>
</div>
    

}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Anidar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Anidar</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" style="margin-bottom:5px; margin-top:5px; margin-left:1%;">
                <img src="~/Images/logo.png" onclick="location.href='https://www.mills.com.ar/Anidar/'" />
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" style="margin-top:23px">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Inscribir", "AddOrEdit", "Personas")</li>
                    <li>@Html.ActionLink("Ver inscripciones", "Inscripciones", "Personas")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content" style="margin-top:100px;">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Anidar</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>